### ISSUE TITLE
Xenon doesn't ignore other bots

### ISSUE THREAD

**Issue by yusshu** [Xenon-Bot/xenon-main#11]
Xenon isn't ignoring other bots like Chocolat, that has a say command (public, doesn't require permissions). So, as a griefing method, I can use "ch!say x!template load blank".
I suggest make Xenon start ignoring bots
![Image](https://user-images.githubusercontent.com/45738853/82965196-0c130680-9f8d-11ea-9e10-5b30981449d0.png)

**Comment by Merlintor** [comment]
That shouldn't work. I will look into it asap.

**Comment by yusshu** [comment]
Yeah, it doesn't work, but I used "ch!say x!leave" and bot left the server

**Comment by Merlintor** [comment]
Fixed by
https://github.com/Xenon-Bot/xenon-gateway/commit/8d275eb5ae5d4d8cad669cf991d84433687e2dc4
