### ISSUE TITLE
Display when a backup exists, but is owned by someone else

### ISSUE THREAD

**Issue by ThatLifeofGames** [Xenon-Bot/xenon-main#13]
It would be good if Xenon showed a different message when a backup exists, but is owned by someone else, it might be less confusing for people.

For example, Xenon could say "There is no backup with the ID XXXXX" when it doesn't exist.
If it is owned by someone else, it could say "The backup with the ID XXXX is owned by someone else"

**Comment by Merlintor** [comment]
I don't think I would want this to happen
