### ISSUE TITLE
Suggestion: Confirmation to load

### ISSUE THREAD

**Issue by HyScript7** [Xenon-Bot/xenon-main#23]
It would be great if you added a confirmation if you are sure to load the backup.
We now have to recreate the server im a dev on because the roles got unasigned for some reason.

**Comment by Merlintor** [comment]
Are you joking? 🤔

**Comment by ThatLifeofGames** [comment]
Closing since this already exists and has done since day 1...

**Comment by HyScript7** [comment]
My bad. I forgot i made a mouse macro to do it automaticly a month or so ago. Im stupid.
