### ISSUE TITLE
Sync message deletion and pins for the last X synced messages

### ISSUE THREAD

**Issue by Merlintor** [Xenon-Bot/xenon-main#40]
This would require a distributed id-translator with high accessibility. Keeping the last 100 message ids per sync would probably be enough.

**Comment by Merlintor** [comment]
Webhooks now support editing and deleting messages. Syncing with these shouldn't be a problem anymore. Especially because those requests don't count into the global ratelimit.

**Comment by Merlintor** [comment]
Saving the id-translator in the sync-document itself would only require one extra db-query per message, so I think that's the best way to store them persistently.

**Comment by Merlintor** [comment]
Syncing pins is actually almost impossible, because the event payload does not contain any information about which message got pinned or unpinned. It just tells you in which channel and guild the pins got updated.

**Comment by ThatLifeofGames** [comment]
I think you can fetch all pins for an entire channel rather than listening for them with an event, i remember fetching pinned messages for vega.

**Comment by Merlintor** [comment]
Yeah, that's true. But then I still don't know which message got pinned / unpinned. It just tells me which messages are pinned now. So I would have to keep an internal cache of the pins to be able to get that info. I don't want to do that for such a minor feature tbh

**Comment by ThatLifeofGames** [comment]
Surely thats what you want for a backup? The pins to be fetched and kept exactly as they are when the backup was created, not how they were the last time they were seen? Or am i understanding what you want to do wrong?

**Comment by Merlintor** [comment]
This issue is about message synch. My goal was to sync when a message gets pinned as well. That's just hard to achieve tho

**Comment by Merlintor** [comment]
I already added pins to backups a few weeks ago. I think there was another issue for that.

**Comment by Merlintor** [comment]
https://github.com/Xenon-Bot/xenon-main/pull/52
