### ISSUE TITLE
Add owner only mode

### ISSUE THREAD

**Issue by Merlintor** [Xenon-Bot/xenon-main#5]
Let the server owner choose if all admins or only the owner is allowed to use the bot

**Comment by ThatLifeofGames** [comment]
If/when this happens, maybe you should also change the **default** permission to owner, that way, there will be less people whining that one of their admins invited xenon to destroy the server, the owner would effectively have to approve the admins using it. This should stop "raiding" of servers with xenon.

**Comment by Merlintor** [comment]
Should this only apply to destructive actions like `backup load`, `chatlog load` and `copy` or also `backup create`, `sync`, `chatlog create`?

**Comment by ThatLifeofGames** [comment]
Yeah, only things that are currently administrator only

**Comment by Merlintor** [comment]
There should probably be a setting for only destructive actions and one for all admin features. Because many users want their admins to be able to create backups. (that was the reason why I changed it from owner only to admin)
